language: node_js
sudo: required
dist: trusty
node_js:
  - 10
cache: npm

addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6

git:
  depth: false
  quiet: true

env:
  - NODE_ENV=production

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - NODE_ENV="" npm install

stages:
  - lint
    if: type = pull_request OR branch = master OR branch = develop
  - test-unit
    if: type = pull_request OR branch = master OR branch = develop
  - integration
    if: type = pull_request OR branch = master OR branch = develop

jobs:
  include:
    - stage: "lint"
      script: npm run lint
    - stage: "test-unit"
      script: npm run test-unit
    - stage: "integration"
      script:
        - npm run build
        - npm run test-integration
